### ISSUE TITLE
/laggchunks broken in current recommended SpongeForge (2611)

### ISSUE THREAD

**Issue by Routhinator** [Time6628/CatClearLag#25]
```
> /laggychunks
[04:12:14] [Server thread/INFO]: Error occurred while executing command: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V
[04:12:14] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'laggychunks' for source DedicatedServer: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V
java.lang.NoSuchMethodError: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V
	at me.time6628.clag.sponge.commands.LaggyChunksCommand.execute(LaggyChunksCommand.java:34) ~[LaggyChunksCommand.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:250) ~[ChildCommandElementExecutor.class:1.12.2-2611-7.1.0-BETA-3002]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2611-7.1.0-BETA-3002]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2611-7.1.0-BETA-3002]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2611-7.1.0-BETA-3002]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:432) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by Time6628** [comment]
https://ore.spongepowered.org/TimeTheCat/CatClearLag/versions/0.8.3

**Comment by WildCatChan** [comment]
https://github.com/Time6628/CatClearLag/blob/8372f27418615c9dee650eb03d91c1b665b3c083/src/main/java/me/time6628/clag/sponge/commands/subcommands/laggychunks/TilesCommand.java#L26
Hello! I found here might be the problem is.

It crashed when you run this command at server console. Because it casts `src` to `Player`, but `src` could be a `net.minecraft.server.dedicated.DedicatedServer`.

**Comment by Time6628** [comment]
Except it won't be, because you should run the command from in-game so it actually does what it's supposed to do.
