### ISSUE TITLE
"Could not pass ChangeInventoryEvent" Keep showing up

### ISSUE THREAD

**Issue by Misaka15539** [Time6628/CatClearLag#34]
This same message keep showing up over and over again in the terminal for no clear reason

`ServerThread/ERROR [Sponge]: Could not pass ChangeInventoryEvent$Pickup$Pre$Impl to Plugin{id=catclearlag, name=CatClearLag, version=0.9.0, description=A plugin to assist in removing lag from your server., source=./mods/CatClearLag-0.9.0.jar}`

**Comment by Misaka15539** [comment]
BTW version info

Minecraft: 1.12.2
SpongeAPI: 7.1.0-70763aa8
Sponge: 1.12.2-7.1.4
SpongeForge: 1.12.2-2768-7.1.4
Minecraft Forge: 14.23.4.2705

**Comment by Time6628** [comment]
Please post the stack trace.

**Comment by Misaka15539** [comment]
There is only one line in the trace:
`java.lang.NullPointerException: null`
It seems to get worse over time. Every line is like this
`[02:52:31]` [Server thread/ERROR] [Sponge]: Could not pass ChangeInventoryEvent$Pickup$Pre$Impl to Plugin{id=catclearlag, name=CatClearLag, version=0.9.0, description=A plugin to assist in removing lag from your server., source=./mods/CatClearLag-0.9.0.jar}
java.lang.NullPointerException: null
[02:52:31] [Server thread/ERROR] [Sponge]: Could not pass ChangeInventoryEvent$Pickup$Pre$Impl to Plugin{id=catclearlag, name=CatClearLag, version=0.9.0, description=A plugin to assist in removing lag from your server., source=./mods/CatClearLag-0.9.0.jar}
java.lang.NullPointerException: null`

**Comment by Time6628** [comment]
Send the full log.

**Comment by Misaka15539** [comment]
[2018-11-26-1.log](https://github.com/Time6628/CatClearLag/files/2615793/2018-11-26-1.log)
[debug-5.log](https://github.com/Time6628/CatClearLag/files/2615794/debug-5.log)

**Comment by johnfriedrich** [comment]
the server already cut the error. See where the error first appeared to get the full error

**Comment by TigerWalts** [comment]
Here's the error with the full stack trace

- spongeforge-1.12.2-2705-7.1.0-BETA-3477.jar
- forge-1.12.2-14.23.4.2707-universal.jar

```
[16:20:57] [Server thread/ERROR] [Sponge]: Could not pass ChangeInventoryEvent$Pickup$Pre$Impl to Plugin{id=catclearlag, name=CatClearLag, version=0.9.0, description=A plugin to assist in removing lag from your server., source=./mods/CatClearLag-0.9.0.jar}
java.lang.NullPointerException: null
        at me.time6628.clag.sponge.handlers.ItemManager.onEntityDespawn(ItemManager.java:48) ~[ItemManager.class:?]
        at org.spongepowered.common.event.listener.PreListener_ItemManager_onEntityDespawn83.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3477]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3477]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3477]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3477]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3477]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:458) [SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3477]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3477]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callPlayerChangeInventoryPickupPreEvent(SpongeCommonEventFactory.java:304) [SpongeCommonEventFactory.class:1.12.2-2705-7.1.0-BETA-3477]
        at net.minecraft.entity.item.EntityItem.handler$onPlayerItemPickup$zga000(EntityItem.java:769) [acl.class:?]
        at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:392) [acl.class:?]
        at realdrops.entities.EntityItemLoot.func_70100_b_(EntityItemLoot.java:163) [EntityItemLoot.class:?]
        at net.minecraft.entity.player.EntityPlayer.redirect$onPlayerCollideEntity$zgp000(EntityPlayer.java:3770) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:600) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:571) [aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zio000(NetHandlerPlayServer.java:2048) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by zsn741656478** [comment]
The same.
https://i.loli.net/2019/01/10/5c36d22c5a689.png
@Time6628 Fix it please.

**Comment by TigerWalts** [comment]
I think this is an incompatibility with Realistic Item Drops.

My guess is that RealDrops might be replacing item entities entirely and when CatClearLag tries to remove the future removal task for a picked up item, it encounters an NPE because a task doesn't exist for that item entity: https://github.com/Funwayguy/RealisticItemDrops/blob/87086eecd2affa8ab3fd5eb8113c9afae306be1a/src/main/java/realdrops/handlers/EventHandler.java#L75

**Comment by jinkhya** [comment]
It also seems to be an issue with ItemPhysic_Full wich is same idea as Realistic Item drops. Catclearlag doesn't clear items either because of that mod. 
That mod is in Project Ozone 3.
