### ISSUE TITLE
Customizing text error console

### ISSUE THREAD

**Issue by Aathoss** [Time6628/CatClearLag#36]
- Forge 1.12.2 - 2768
- Sponge 1.12.2-2768-7.1.5-RC3523
- CatClearLag 0.9.0

File : messages.conf
"Clearing Items Message"="UniTeck à supprimer &f%d items au sol."
"Message Color"="LIGHT_PURPLE" 
"Prefix="&5[UniTeck-Lag] "
"Warning Message"="&4UniTeck &cVa faire le grand ménage !! &f%d seconds."

Error console : 
`[13:13:00] [pool-3-thread-88/ERROR] [Sponge]: The Scheduler tried to run the task CatClearLag Removal Warnings owned by Plugin{id=catclearlag, name=CatClearLag, version=0.9.0, description=A plugin to assist in removing lag from your server., source=./mods/CatClearLag-0.9.0.jar}, but an error occured.
java.lang.NullPointerException: null
at me.time6628.clag.sponge.Messages.getPrefix(Messages.java:19) ~[Messages.class:?]
at me.time6628.clag.sponge.Messages.getWarningMsg(Messages.java:32) ~[Messages.class:?]
at me.time6628.clag.sponge.runnables.ItemClearingWarning.run(ItemClearingWarning.java:20) ~[ItemClearingWarning.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2768-7.1.5-RC3523]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2768-7.1.5-RC3523]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

This message this products to each clearlag broadcast.
Except that he can not display custom text
So he gives this error

**Comment by Wubsy** [comment]
Remove the "&" at the beginning of your warning message.

**Comment by Aathoss** [comment]
My message contains this exactly sorry to mislead all to their

"Clearing Items Message"="UniTeck à supprimer &f%d items au sol."
"Message Color"="LIGHT_PURPLE" 
"Prefix="&5[UniTeck-Lag] "
"Warning Message"="&4UniTeck &cVa faire le grand ménage !! &f%d seconds."

**Comment by Time6628** [comment]
Reset your messages config.

**Comment by Aathoss** [comment]
Already done
Writing my personalized message does not work better
Even being careful not to touch your set up :/
