### ISSUE TITLE
/laggychunks returns an error.

### ISSUE THREAD

**Issue by MeltPels** [Time6628/CatClearLag#43]
On Spongeforge (version below) running the Direwolf20 2.5.0 pack running the /laggychunks command returns an error (error below). I'm using CatClearLag 0.8

```
[28-07-2019 12:18:34] SpongeForge
[28-07-2019 12:18:34]     Minecraft: 1.12.2
[28-07-2019 12:18:34]     SpongeAPI: 7.1.0-fb496dbf0
[28-07-2019 12:18:34]     Sponge: 1.12.2-7.1.7-SNAPSHOT
[28-07-2019 12:18:34]     SpongeForge: 1.12.2-2825-7.1.7-RC3770
[28-07-2019 12:18:34]     Minecraft Forge: 14.23.5.2821
[28-07-2019 12:18:34]     JVM: 1.8.0_212/64-bit (Oracle Corporation)
[28-07-2019 12:18:34]     OS: Linux (3.10.0-862.3.2.el7.x86_64/amd64)
```

```

[28-07-2019 12:14:10] Thanks_again ran the command: /laggychunks tiles
[28-07-2019 12:14:10] Error occurred while executing command 'laggychunks tiles' for source EntityPlayerMP['Thanks_again'/2209, l='direwolf201-12-2-5-0', x=-9.50, y=63.00, z=287.50]: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V
[28-07-2019 12:14:10] java.lang.NoSuchMethodError: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V
[28-07-2019 12:14:10] at me.time6628.clag.sponge.commands.subcommands.laggychunks.TilesCommand.execute(TilesCommand.java:43) ~[TilesCommand.class:?]
[28-07-2019 12:14:10] at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2825-7.1.7-RC3770]
[28-07-2019 12:14:10] at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2825-7.1.7-RC3770]
[28-07-2019 12:14:10] at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2825-7.1.7-RC3770]
[28-07-2019 12:14:10] at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:337) [SpongeCommandManager.class:1.12.2-2825-7.1.7-RC3770]
[28-07-2019 12:14:10] at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1156) [dh.class:?]
[28-07-2019 12:14:10] at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
[28-07-2019 12:14:10] at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
[28-07-2019 12:14:10] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
[28-07-2019 12:14:10] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
[28-07-2019 12:14:10] at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2825-7.1.7-RC3770]
[28-07-2019 12:14:10] at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlk000(SourceFile:539) [hv$1.class:?]
[28-07-2019 12:14:10] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
[28-07-2019 12:14:10] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
[28-07-2019 12:14:10] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
[28-07-2019 12:14:10] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
[28-07-2019 12:14:10] at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.7-RC3770]
[28-07-2019 12:14:10] at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
[28-07-2019 12:14:10] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
[28-07-2019 12:14:10] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
[28-07-2019 12:14:10] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
[28-07-2019 12:14:10] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
[28-07-2019 12:14:10] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by MeltPels** [comment]
Upgrading to 0.8.1. worked. Closing the issue, my bad.
