### ISSUE TITLE
Console spam on routine hostile check

### ISSUE THREAD

**Issue by MeltPels** [Time6628/CatClearLag#44]
Hey, I updated to the latest version and am getting console spam ever since. 
Running on version 0.8.1 

Sponge version:

```
[29-07-2019 23:17:57] SpongeForge
[29-07-2019 23:17:57]     Minecraft: 1.12.2
[29-07-2019 23:17:57]     SpongeAPI: 7.1.0-fb496dbf0
[29-07-2019 23:17:57]     Sponge: 1.12.2-7.1.7-SNAPSHOT
[29-07-2019 23:17:57]     SpongeForge: 1.12.2-2825-7.1.7-RC3770
[29-07-2019 23:17:57]     Minecraft Forge: 14.23.5.2821
[29-07-2019 23:17:57]     JVM: 1.8.0_212/64-bit (Oracle Corporation)
[29-07-2019 23:17:57]     OS: Linux (3.10.0-862.3.2.el7.x86_64/amd64)
```

Error:
```
[29-07-2019 23:13:41] The Scheduler tried to run the task CatClearLag hostile checker owned by Plugin{id=catclearlag, name=CatClearLag, version=0.8.1, description=A plugin to assist in removing lag from your server., source=/home/smpicnic/server/data/./mods/plugins/CatClearLag-0.8.1.jar}, but an error occured.
[29-07-2019 23:13:41] java.lang.NullPointerException: null
[29-07-2019 23:13:41] at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_212]
[29-07-2019 23:13:41] at java.util.function.Predicate.and(Predicate.java:68) ~[?:1.8.0_212]
[29-07-2019 23:13:41] at me.time6628.clag.sponge.EntityRemover.<init>(EntityRemover.java:40) ~[EntityRemover.class:?]
[29-07-2019 23:13:41] at me.time6628.clag.sponge.CatClearLag.getXPOrbs(CatClearLag.java:180) ~[CatClearLag.class:?]
[29-07-2019 23:13:41] at me.time6628.clag.sponge.runnables.EntityChecker.run(EntityChecker.java:20) ~[EntityChecker.class:?]
[29-07-2019 23:13:41] at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2825-7.1.7-RC3770]
[29-07-2019 23:13:41] at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2825-7.1.7-RC3770]
[29-07-2019 23:13:41] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
[29-07-2019 23:13:41] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
[29-07-2019 23:13:41] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
[29-07-2019 23:13:41] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
[29-07-2019 23:13:41] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by MeltPels** [comment]
Seems to be the same issue as mentioned here:

https://github.com/Time6628/CatClearLag/issues/19

**Comment by MeltPels** [comment]
Why was this closed, neither this nor the original report got any support. Is there a fix I've seemed to have missed?
