### ISSUE TITLE
Error with my server

### ISSUE THREAD

**Issue by pjindras** [Time6628/CatClearLag#55]
Hello, i have this error on my server 1.12.2 sponge & forge -> lastest forge + lastest recommended sponge

`[18:48:04] [pool-3-thread-3/ERROR] [Sponge]: The Scheduler tried to run the task CatClearLag Item Remover owned by Plugin{id=catclearlag, name=CatClearLag, version=0.9.0, description=A plugin to assist in removing lag from your server., source=.\mods\CatClearLag-0.9.0.jar}, but an error occured.
java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=pool-3-thread-3, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
        at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:121) ~[SpongeCauseStackManager.class:1.12.2-2838-7.1.10]
        at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:136) ~[SpongeCauseStackManager.class:1.12.2-2838-7.1.10]
        at net.minecraft.entity.Entity.handler$zee000$impl$createDestructionEventOnDeath(Entity.java:7969) ~[vg.class:?]
        at net.minecraft.entity.Entity.setDead(Entity.java:317) ~[vg.class:?]
        at net.minecraft.entity.Entity.remove(Entity.java:5351) ~[vg.class:?]
        at me.time6628.clag.sponge.EntityRemover.lambda$removeEntities$1(EntityRemover.java:37) ~[EntityRemover.class:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_241]
        at me.time6628.clag.sponge.EntityRemover.removeEntities(EntityRemover.java:36) ~[EntityRemover.class:?]
        at me.time6628.clag.sponge.utils.EntityHelpers.clearGroundItems(EntityHelpers.java:34) ~[EntityHelpers.class:?]
        at me.time6628.clag.sponge.runnables.ItemClearer.run(ItemClearer.java:15) ~[ItemClearer.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.10]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.1.10]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

**Comment by Time6628** [comment]
https://cdn.discordapp.com/attachments/339868227846799360/676912099695263747/CatClearLag-0.9.3.jar
