### ISSUE TITLE
Crash-report

### ISSUE THREAD

**Issue by Scheshi** [Time6628/CatClearLag#65]
[17:48:58] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task CatClearLag Item Remover owned by Plugin{id=catclearlag, name=CatClearLag, version=0.9.0, description=A plugin to assist in removing lag from your server., source=/home/zombie/./mods/plugins/CatClearLag-0.9.5.1.jar}, but an error occured.
java.lang.NullPointerException: null
	at me.time6628.clag.sponge.Messages.getPrefix(Messages.java:19) ~[Messages.class:?]
	at me.time6628.clag.sponge.Messages.getClearMsg(Messages.java:28) ~[Messages.class:?]
	at me.time6628.clag.sponge.Messages.getClearMsg(Messages.java:23) ~[Messages.class:?]
	at me.time6628.clag.sponge.runnables.ItemClearer.run(ItemClearer.java:25) ~[ItemClearer.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.1.7-RC3924]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3924]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2838-7.1.7-RC3924]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3924]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2838-7.1.7-RC3924]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_242]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.1.7-RC3924]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.1.7-RC3924]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2838-7.1.7-RC3924]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:454) [SpongeMod.class:1.12.2-2838-7.1.7-RC3924]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:752) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:702) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Time6628** [comment]
Download the update from discord in the announcements channel.

**Comment by Scheshi** [comment]
Again this crash

**Comment by yerbuky** [comment]
Delete file catclearlag.cfg
