### ISSUE TITLE
[Sponge]: The Scheduler tried to run the task CatClearLag, but ran into an error

### ISSUE THREAD

**Issue by MoonTechGaming** [Time6628/CatClearLag#68]
As stated above:
[11:23:15] [pool-3-thread-115/ERROR] [Sponge]: The Scheduler tried to run the task CatClearLag Item Remover owned by Plugin{id=catclearlag, name=CatClearLag, version=0.9.0, description=A plugin to assist in removing lag from your server., source=./mods/CatClearLag-0.9.0.jar}, but an error occured.
java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=pool-3-thread-115, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:121) ~[SpongeCauseStackManager.class:1.12.2-2838-7.2.3-RC4035]
at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:136) ~[SpongeCauseStackManager.class:1.12.2-2838-7.2.3-RC4035]
at net.minecraft.entity.Entity.handler$zef000$impl$createDestructionEventOnDeath(Entity.java:7984) ~[vg.class:?]
at net.minecraft.entity.Entity.setDead(Entity.java:317) ~[vg.class:?]
at net.minecraft.entity.Entity.remove(Entity.java:5358) ~[vg.class:?]
at me.time6628.clag.sponge.EntityRemover.lambda$removeEntities$1(EntityRemover.java:37) ~[EntityRemover.class:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_242]
at me.time6628.clag.sponge.EntityRemover.removeEntities(EntityRemover.java:36) ~[EntityRemover.class:?]
at me.time6628.clag.sponge.utils.EntityHelpers.clearGroundItems(EntityHelpers.java:34) ~[EntityHelpers.class:?]
at me.time6628.clag.sponge.runnables.ItemClearer.run(ItemClearer.java:15) ~[ItemClearer.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.2.3-RC4035]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.2.3-RC4035]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

Running Sponge-1.12.2-2838-7.2.3-RC4035
On Linux Ubuntu
Server is running within an docker with pterodactyl

More info:

Clearlag also seems to not work.
I used to run spongeforge-1.12.2-7.1.0, updated to the new version and the timer doesnt work

**Comment by Time6628** [comment]
Update the plugin to the one on curseforge.
